name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
      - 'hotfix-*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.head_ref && true || false }}


jobs:
  build_8:
    name: "Build JDK 1.8"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
