name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'
      - 'hotfix-*'

jobs:
  build_8:
    name: "Build JDK 1.8"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
